// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: affiliate_imports.sql

package queries

import (
	"context"
	"database/sql"
)

const getAffiliateImportBatchByID = `-- name: GetAffiliateImportBatchByID :one
SELECT
	id,
	filename,
	product_count,
	file_size_bytes,
	csv_row_count,
	created_at,
	created_by,
	created_by_name
FROM tbl_affiliate_import_batches
WHERE id = ?
`

type GetAffiliateImportBatchByIDRow struct {
	ID            int64
	Filename      string
	ProductCount  int64
	FileSizeBytes int64
	CsvRowCount   int64
	CreatedAt     string
	CreatedBy     sql.NullInt64
	CreatedByName string
}

func (q *Queries) GetAffiliateImportBatchByID(ctx context.Context, id int64) (GetAffiliateImportBatchByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAffiliateImportBatchByID, id)
	var i GetAffiliateImportBatchByIDRow
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.ProductCount,
		&i.FileSizeBytes,
		&i.CsvRowCount,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.CreatedByName,
	)
	return i, err
}

const getAffiliateProductsByImportBatchID = `-- name: GetAffiliateProductsByImportBatchID :many
SELECT
	p.id,
	p.affiliate_url,
	p.product_url,
	p.shop_id,
	p.item_id,
	p.name,
	p.brand,
	p.price_display,
	p.thumbnail_url,
	p.sort_order,
	p.import_batch_id,
	p.sales,
	p.affiliated_shop_id,
	COALESCE(s.brand_name, '') AS shop_brand_name,
	p.commission_rate,
	p.commission,
	p.click_count,
	p.created_at,
	p.updated_at
FROM tbl_affiliate_products p
LEFT JOIN tbl_affiliated_product_shops s ON s.id = p.affiliated_shop_id
WHERE p.import_batch_id = ?
ORDER BY p.sort_order ASC, p.id ASC
`

type GetAffiliateProductsByImportBatchIDRow struct {
	ID               int64
	AffiliateUrl     string
	ProductUrl       string
	ShopID           string
	ItemID           string
	Name             string
	Brand            string
	PriceDisplay     string
	ThumbnailUrl     string
	SortOrder        int64
	ImportBatchID    int64
	Sales            string
	AffiliatedShopID sql.NullInt64
	ShopBrandName    string
	CommissionRate   string
	Commission       string
	ClickCount       int64
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) GetAffiliateProductsByImportBatchID(ctx context.Context, importBatchID int64) ([]GetAffiliateProductsByImportBatchIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getAffiliateProductsByImportBatchID, importBatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAffiliateProductsByImportBatchIDRow
	for rows.Next() {
		var i GetAffiliateProductsByImportBatchIDRow
		if err := rows.Scan(
			&i.ID,
			&i.AffiliateUrl,
			&i.ProductUrl,
			&i.ShopID,
			&i.ItemID,
			&i.Name,
			&i.Brand,
			&i.PriceDisplay,
			&i.ThumbnailUrl,
			&i.SortOrder,
			&i.ImportBatchID,
			&i.Sales,
			&i.AffiliatedShopID,
			&i.ShopBrandName,
			&i.CommissionRate,
			&i.Commission,
			&i.ClickCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAffiliateImportBatch = `-- name: InsertAffiliateImportBatch :one
INSERT INTO tbl_affiliate_import_batches (
	filename,
	product_count,
	file_size_bytes,
	csv_row_count,
	created_by,
	created_by_name
)
VALUES (?, 0, ?, ?, ?, ?)
RETURNING id
`

type InsertAffiliateImportBatchParams struct {
	Filename      string
	FileSizeBytes int64
	CsvRowCount   int64
	CreatedBy     sql.NullInt64
	CreatedByName string
}

func (q *Queries) InsertAffiliateImportBatch(ctx context.Context, arg InsertAffiliateImportBatchParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertAffiliateImportBatch,
		arg.Filename,
		arg.FileSizeBytes,
		arg.CsvRowCount,
		arg.CreatedBy,
		arg.CreatedByName,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateAffiliateImportBatchCount = `-- name: UpdateAffiliateImportBatchCount :exec
UPDATE tbl_affiliate_import_batches
SET product_count = ?
WHERE id = ?
`

type UpdateAffiliateImportBatchCountParams struct {
	ProductCount int64
	ID           int64
}

func (q *Queries) UpdateAffiliateImportBatchCount(ctx context.Context, arg UpdateAffiliateImportBatchCountParams) error {
	_, err := q.db.ExecContext(ctx, updateAffiliateImportBatchCount, arg.ProductCount, arg.ID)
	return err
}
