// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: affiliate_products.sql

package queries

import (
	"context"
	"database/sql"
)

const deleteAffiliateProduct = `-- name: DeleteAffiliateProduct :exec
DELETE FROM tbl_affiliate_products
WHERE id = ?
`

func (q *Queries) DeleteAffiliateProduct(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAffiliateProduct, id)
	return err
}

const getAffiliateProductByID = `-- name: GetAffiliateProductByID :one
SELECT
	p.id,
	p.affiliate_url,
	p.product_url,
	p.shop_id,
	p.item_id,
	p.name,
	p.brand,
	p.price_display,
	p.thumbnail_url,
	p.sort_order,
	p.import_batch_id,
	p.sales,
	p.affiliated_shop_id,
	COALESCE(s.brand_name, '') AS shop_brand_name,
	p.commission_rate,
	p.commission,
	p.click_count,
	p.created_at,
	p.updated_at
FROM tbl_affiliate_products p
LEFT JOIN tbl_affiliated_product_shops s ON s.id = p.affiliated_shop_id
WHERE p.id = ?
`

type GetAffiliateProductByIDRow struct {
	ID               int64
	AffiliateUrl     string
	ProductUrl       string
	ShopID           string
	ItemID           string
	Name             string
	Brand            string
	PriceDisplay     string
	ThumbnailUrl     string
	SortOrder        int64
	ImportBatchID    int64
	Sales            string
	AffiliatedShopID sql.NullInt64
	ShopBrandName    string
	CommissionRate   string
	Commission       string
	ClickCount       int64
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) GetAffiliateProductByID(ctx context.Context, id int64) (GetAffiliateProductByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAffiliateProductByID, id)
	var i GetAffiliateProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.AffiliateUrl,
		&i.ProductUrl,
		&i.ShopID,
		&i.ItemID,
		&i.Name,
		&i.Brand,
		&i.PriceDisplay,
		&i.ThumbnailUrl,
		&i.SortOrder,
		&i.ImportBatchID,
		&i.Sales,
		&i.AffiliatedShopID,
		&i.ShopBrandName,
		&i.CommissionRate,
		&i.Commission,
		&i.ClickCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllAffiliateProducts = `-- name: GetAllAffiliateProducts :many
SELECT
	p.id,
	p.affiliate_url,
	p.product_url,
	p.shop_id,
	p.item_id,
	p.name,
	p.brand,
	p.price_display,
	p.thumbnail_url,
	p.sort_order,
	p.import_batch_id,
	p.sales,
	p.affiliated_shop_id,
	COALESCE(s.brand_name, '') AS shop_brand_name,
	p.commission_rate,
	p.commission,
	p.click_count,
	p.created_at,
	p.updated_at
FROM tbl_affiliate_products p
LEFT JOIN tbl_affiliated_product_shops s ON s.id = p.affiliated_shop_id
ORDER BY p.sort_order ASC, p.id ASC
`

type GetAllAffiliateProductsRow struct {
	ID               int64
	AffiliateUrl     string
	ProductUrl       string
	ShopID           string
	ItemID           string
	Name             string
	Brand            string
	PriceDisplay     string
	ThumbnailUrl     string
	SortOrder        int64
	ImportBatchID    int64
	Sales            string
	AffiliatedShopID sql.NullInt64
	ShopBrandName    string
	CommissionRate   string
	Commission       string
	ClickCount       int64
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) GetAllAffiliateProducts(ctx context.Context) ([]GetAllAffiliateProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllAffiliateProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAffiliateProductsRow
	for rows.Next() {
		var i GetAllAffiliateProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.AffiliateUrl,
			&i.ProductUrl,
			&i.ShopID,
			&i.ItemID,
			&i.Name,
			&i.Brand,
			&i.PriceDisplay,
			&i.ThumbnailUrl,
			&i.SortOrder,
			&i.ImportBatchID,
			&i.Sales,
			&i.AffiliatedShopID,
			&i.ShopBrandName,
			&i.CommissionRate,
			&i.Commission,
			&i.ClickCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementAffiliateProductClickCount = `-- name: IncrementAffiliateProductClickCount :exec
UPDATE tbl_affiliate_products
SET
	click_count = click_count + 1,
	updated_at = datetime('now')
WHERE id = ?
`

func (q *Queries) IncrementAffiliateProductClickCount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementAffiliateProductClickCount, id)
	return err
}

const insertAffiliateProduct = `-- name: InsertAffiliateProduct :one
INSERT INTO tbl_affiliate_products (
	affiliate_url,
	product_url,
	shop_id,
	item_id,
	name,
	brand,
	price_display,
	thumbnail_url,
	sort_order,
	import_batch_id,
	sales,
	affiliated_shop_id,
	commission_rate,
	commission
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertAffiliateProductParams struct {
	AffiliateUrl     string
	ProductUrl       string
	ShopID           string
	ItemID           string
	Name             string
	Brand            string
	PriceDisplay     string
	ThumbnailUrl     string
	SortOrder        int64
	ImportBatchID    int64
	Sales            string
	AffiliatedShopID sql.NullInt64
	CommissionRate   string
	Commission       string
}

func (q *Queries) InsertAffiliateProduct(ctx context.Context, arg InsertAffiliateProductParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertAffiliateProduct,
		arg.AffiliateUrl,
		arg.ProductUrl,
		arg.ShopID,
		arg.ItemID,
		arg.Name,
		arg.Brand,
		arg.PriceDisplay,
		arg.ThumbnailUrl,
		arg.SortOrder,
		arg.ImportBatchID,
		arg.Sales,
		arg.AffiliatedShopID,
		arg.CommissionRate,
		arg.Commission,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateAffiliateProduct = `-- name: UpdateAffiliateProduct :exec
UPDATE tbl_affiliate_products
SET
	affiliate_url = ?,
	product_url = ?,
	shop_id = ?,
	item_id = ?,
	name = ?,
	brand = ?,
	price_display = ?,
	thumbnail_url = ?,
	sort_order = ?,
	sales = ?,
	affiliated_shop_id = ?,
	commission_rate = ?,
	commission = ?,
	updated_at = datetime('now')
WHERE id = ?
`

type UpdateAffiliateProductParams struct {
	AffiliateUrl     string
	ProductUrl       string
	ShopID           string
	ItemID           string
	Name             string
	Brand            string
	PriceDisplay     string
	ThumbnailUrl     string
	SortOrder        int64
	Sales            string
	AffiliatedShopID sql.NullInt64
	CommissionRate   string
	Commission       string
	ID               int64
}

func (q *Queries) UpdateAffiliateProduct(ctx context.Context, arg UpdateAffiliateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateAffiliateProduct,
		arg.AffiliateUrl,
		arg.ProductUrl,
		arg.ShopID,
		arg.ItemID,
		arg.Name,
		arg.Brand,
		arg.PriceDisplay,
		arg.ThumbnailUrl,
		arg.SortOrder,
		arg.Sales,
		arg.AffiliatedShopID,
		arg.CommissionRate,
		arg.Commission,
		arg.ID,
	)
	return err
}
