// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: student.sql

package queries

import (
	"context"
	"database/sql"
)

const getActiveStudents = `-- name: GetActiveStudents :many
SELECT id, name, currency, contact, rate_per_class, parent_name, assigned_color, status, created_at, updated_at
FROM tbl_students
WHERE status = 'active'
ORDER BY name ASC
`

func (q *Queries) GetActiveStudents(ctx context.Context) ([]TblStudent, error) {
	rows, err := q.db.QueryContext(ctx, getActiveStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TblStudent
	for rows.Next() {
		var i TblStudent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Currency,
			&i.Contact,
			&i.RatePerClass,
			&i.ParentName,
			&i.AssignedColor,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllStudents = `-- name: GetAllStudents :many
SELECT id, name, currency, contact, rate_per_class, parent_name, assigned_color, status, created_at, updated_at
FROM tbl_students
ORDER BY created_at DESC
`

func (q *Queries) GetAllStudents(ctx context.Context) ([]TblStudent, error) {
	rows, err := q.db.QueryContext(ctx, getAllStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TblStudent
	for rows.Next() {
		var i TblStudent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Currency,
			&i.Contact,
			&i.RatePerClass,
			&i.ParentName,
			&i.AssignedColor,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentByName = `-- name: GetStudentByName :one
SELECT COUNT(*) as count FROM tbl_students WHERE name = ?
`

func (q *Queries) GetStudentByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getStudentByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getStudentIDByName = `-- name: GetStudentIDByName :one
SELECT id FROM tbl_students WHERE name = ?
`

func (q *Queries) GetStudentIDByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getStudentIDByName, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertStudent = `-- name: InsertStudent :exec
INSERT INTO tbl_students (name, currency, contact, rate_per_class, parent_name, assigned_color, status)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertStudentParams struct {
	Name          string
	Currency      string
	Contact       sql.NullString
	RatePerClass  float64
	ParentName    sql.NullString
	AssignedColor string
	Status        string
}

func (q *Queries) InsertStudent(ctx context.Context, arg InsertStudentParams) error {
	_, err := q.db.ExecContext(ctx, insertStudent,
		arg.Name,
		arg.Currency,
		arg.Contact,
		arg.RatePerClass,
		arg.ParentName,
		arg.AssignedColor,
		arg.Status,
	)
	return err
}
