// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_log.sql

package queries

import (
	"context"
	"database/sql"
)

const getAllLogs = `-- name: GetAllLogs :many
SELECT l.id, l.module, l.message, l.created_by, l.created_at,
    COALESCE(t.name, l.created_by_name, '') as created_by_name
FROM tbl_logs l
LEFT JOIN tbl_teachers t ON l.created_by = t.id
ORDER BY l.created_at DESC
`

type GetAllLogsRow struct {
	ID            int64
	Module        string
	Message       string
	CreatedBy     sql.NullInt64
	CreatedAt     string
	CreatedByName string
}

func (q *Queries) GetAllLogs(ctx context.Context) ([]GetAllLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllLogsRow
	for rows.Next() {
		var i GetAllLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.Module,
			&i.Message,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertLog = `-- name: InsertLog :exec
INSERT INTO tbl_logs (
    module,
    message,
    created_by,
    created_by_name,
    created_at
) VALUES (
    ?, ?, ?, ?, datetime('now')
)
`

type InsertLogParams struct {
	Module        string
	Message       string
	CreatedBy     sql.NullInt64
	CreatedByName sql.NullString
}

func (q *Queries) InsertLog(ctx context.Context, arg InsertLogParams) error {
	_, err := q.db.ExecContext(ctx, insertLog,
		arg.Module,
		arg.Message,
		arg.CreatedBy,
		arg.CreatedByName,
	)
	return err
}
