// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teacher.sql

package queries

import (
	"context"
	"database/sql"
)

const approveTeacher = `-- name: ApproveTeacher :exec
UPDATE tbl_teachers SET status = 'approved', updated_at = CURRENT_TIMESTAMP WHERE id = ? AND status = 'pending'
`

func (q *Queries) ApproveTeacher(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, approveTeacher, id)
	return err
}

const getAllTeachers = `-- name: GetAllTeachers :many
SELECT id, name, birthdate, address, joining_date, mobile_number, email, certifications, assigned_color, rate_per_class, currency, drive_url, sex, password, template, created_at, updated_at, status
FROM tbl_teachers
ORDER BY CASE status WHEN 'pending' THEN 0 ELSE 1 END, name ASC
`

type GetAllTeachersRow struct {
	ID             int64
	Name           string
	Birthdate      string
	Address        string
	JoiningDate    string
	MobileNumber   string
	Email          string
	Certifications sql.NullString
	AssignedColor  string
	RatePerClass   float64
	Currency       string
	DriveUrl       string
	Sex            sql.NullString
	Password       string
	Template       sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	Status         string
}

func (q *Queries) GetAllTeachers(ctx context.Context) ([]GetAllTeachersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllTeachers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTeachersRow
	for rows.Next() {
		var i GetAllTeachersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Birthdate,
			&i.Address,
			&i.JoiningDate,
			&i.MobileNumber,
			&i.Email,
			&i.Certifications,
			&i.AssignedColor,
			&i.RatePerClass,
			&i.Currency,
			&i.DriveUrl,
			&i.Sex,
			&i.Password,
			&i.Template,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApprovedTeachers = `-- name: GetApprovedTeachers :many
SELECT id, name, birthdate, address, joining_date, mobile_number, email, certifications, assigned_color, rate_per_class, currency, drive_url, sex, password, template, created_at, updated_at, status
FROM tbl_teachers
WHERE status = 'approved'
ORDER BY name ASC
`

type GetApprovedTeachersRow struct {
	ID             int64
	Name           string
	Birthdate      string
	Address        string
	JoiningDate    string
	MobileNumber   string
	Email          string
	Certifications sql.NullString
	AssignedColor  string
	RatePerClass   float64
	Currency       string
	DriveUrl       string
	Sex            sql.NullString
	Password       string
	Template       sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	Status         string
}

func (q *Queries) GetApprovedTeachers(ctx context.Context) ([]GetApprovedTeachersRow, error) {
	rows, err := q.db.QueryContext(ctx, getApprovedTeachers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetApprovedTeachersRow
	for rows.Next() {
		var i GetApprovedTeachersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Birthdate,
			&i.Address,
			&i.JoiningDate,
			&i.MobileNumber,
			&i.Email,
			&i.Certifications,
			&i.AssignedColor,
			&i.RatePerClass,
			&i.Currency,
			&i.DriveUrl,
			&i.Sex,
			&i.Password,
			&i.Template,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeacherByEmail = `-- name: GetTeacherByEmail :one
SELECT id, name, email, password, status FROM tbl_teachers WHERE email = ?
`

type GetTeacherByEmailRow struct {
	ID       int64
	Name     string
	Email    string
	Password string
	Status   string
}

func (q *Queries) GetTeacherByEmail(ctx context.Context, email string) (GetTeacherByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getTeacherByEmail, email)
	var i GetTeacherByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Status,
	)
	return i, err
}

const getTeacherByID = `-- name: GetTeacherByID :one
SELECT id, name, template FROM tbl_teachers WHERE id = ?
`

type GetTeacherByIDRow struct {
	ID       int64
	Name     string
	Template sql.NullString
}

func (q *Queries) GetTeacherByID(ctx context.Context, id int64) (GetTeacherByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTeacherByID, id)
	var i GetTeacherByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.Template)
	return i, err
}

const getTeacherByName = `-- name: GetTeacherByName :one
SELECT COUNT(*) as count FROM tbl_teachers WHERE name = ?
`

func (q *Queries) GetTeacherByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTeacherByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTeacherCountByEmail = `-- name: GetTeacherCountByEmail :one
SELECT COUNT(*) as count FROM tbl_teachers WHERE email = ?
`

func (q *Queries) GetTeacherCountByEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTeacherCountByEmail, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTeacherIDByName = `-- name: GetTeacherIDByName :one
SELECT id FROM tbl_teachers WHERE name = ?
`

func (q *Queries) GetTeacherIDByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTeacherIDByName, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTeacher = `-- name: InsertTeacher :exec
INSERT INTO tbl_teachers (name, birthdate, address, joining_date, mobile_number, email, certifications, assigned_color, rate_per_class, currency, drive_url, sex, password, status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTeacherParams struct {
	Name           string
	Birthdate      string
	Address        string
	JoiningDate    string
	MobileNumber   string
	Email          string
	Certifications sql.NullString
	AssignedColor  string
	RatePerClass   float64
	Currency       string
	DriveUrl       string
	Sex            sql.NullString
	Password       string
	Status         string
}

func (q *Queries) InsertTeacher(ctx context.Context, arg InsertTeacherParams) error {
	_, err := q.db.ExecContext(ctx, insertTeacher,
		arg.Name,
		arg.Birthdate,
		arg.Address,
		arg.JoiningDate,
		arg.MobileNumber,
		arg.Email,
		arg.Certifications,
		arg.AssignedColor,
		arg.RatePerClass,
		arg.Currency,
		arg.DriveUrl,
		arg.Sex,
		arg.Password,
		arg.Status,
	)
	return err
}

const updateTeacherTemplate = `-- name: UpdateTeacherTemplate :exec
UPDATE tbl_teachers SET template = ? WHERE id = ?
`

type UpdateTeacherTemplateParams struct {
	Template sql.NullString
	ID       int64
}

func (q *Queries) UpdateTeacherTemplate(ctx context.Context, arg UpdateTeacherTemplateParams) error {
	_, err := q.db.ExecContext(ctx, updateTeacherTemplate, arg.Template, arg.ID)
	return err
}
