package cmd

import "errors"

var (
	ErrInvalidTeacherID          = errors.New("invalid teacher ID")
	ErrForbidden                 = errors.New("forbidden")
	ErrUnauthorized              = errors.New("unauthorized")
	ErrMissingRequiredParameters = errors.New("missing required parameters")
	ErrMissingNumericValue       = errors.New("missing numeric value")
	ErrMissingIntegerValue       = errors.New("missing integer value")

	ErrEndDateBeforeStart     = errors.New("end date must be after start date")
	ErrMissingDateRange       = errors.New("missing date range")
	ErrInvalidDateRange       = errors.New("invalid date range")
	ErrStartDateRequired      = errors.New("start date is required")
	ErrEndDateRequired        = errors.New("end date is required")
	ErrInvalidStartDateFormat = errors.New("invalid start date format")
	ErrInvalidEndDateFormat   = errors.New("invalid end date format")
	ErrInvalidDateFormat      = errors.New("invalid date format")
	ErrDateRequired           = errors.New("date is required")
	ErrDateTimeInPast         = errors.New("date and time cannot be in the past")

	ErrStudentRequired                       = errors.New("student is required")
	ErrTeacherRequired                       = errors.New("teacher is required")
	ErrStartTimeRequired                     = errors.New("start time is required")
	ErrStartAndEndTimesRequired              = errors.New("start and end times are required")
	ErrDurationMustBePositive                = errors.New("duration must be greater than zero")
	ErrRateMustBePositive                    = errors.New("rate must be greater than zero")
	ErrRateCannotBeNegative                  = errors.New("rate cannot be negative")
	ErrCurrencyRequired                      = errors.New("currency is required")
	ErrInvalidCurrency                       = errors.New("invalid currency. Must be KRW, CAD, YEN, or PHP")
	ErrInvalidStatus                         = errors.New("invalid status")
	ErrReasonRequired                        = errors.New("reason is required")
	ErrReasonRequiredForDeletion             = errors.New("[CLASS] reason is required for deletion")
	ErrReasonRequiredForCancelledRescheduled = errors.New("[CLASS] reason is required for cancelled or rescheduled classes")
	ErrScheduledClassNotFound                = errors.New("[SCHEDULE] scheduled class not found")
	ErrScheduledClassNotInScheduledStatus    = errors.New("[SCHEDULE] scheduled class is not in scheduled status")
	ErrClassRecordDoesNotMatchScheduledClass = errors.New("[SCHEDULE] class record does not match scheduled class")
	ErrOnlyScheduledClassesCanBeCancelled    = errors.New("[SCHEDULE] only scheduled classes can be cancelled")
	ErrOnlyScheduledClassesCanBeDeleted      = errors.New("[SCHEDULE] only scheduled classes can be deleted")
	ErrNoScheduledClassesInSeries            = errors.New("[SCHEDULE] no scheduled classes found in this series")
	ErrSelectAtLeastOneDateForSeries         = errors.New("[SCHEDULE] select at least one date for this series")
	ErrCannotRemovePastSeriesSessions        = errors.New("[SCHEDULE] past sessions in this series cannot be removed when applying to this and future classes only")
	ErrSelectAtLeastTwoDatesForRepeating     = errors.New("[SCHEDULE] select at least two dates for repeating classes")
	ErrSelectAtLeastOneDateToCreate          = errors.New("[SCHEDULE] select at least one date to create")

	ErrInvalidGoogleSpreadsheetURL  = errors.New("[PROCESS] invalid Google Spreadsheet URL")
	ErrGoogleSpreadsheetURLRequired = errors.New("[PROCESS] google spreadsheet url is required")
	ErrNameInvalidCharacters        = errors.New("[PROCESS] name must contain only letters, periods, dashes, and spaces")

	ErrNameRequired                 = errors.New("name is required")
	ErrRatePerClassCannotBeNegative = errors.New("rate per class cannot be negative")
	ErrAssignedColorRequired        = errors.New("assigned color is required")
	ErrInvalidStudentStatus         = errors.New("invalid status. Must be active or inactive")
	ErrInactiveReasonRequired       = errors.New("inactive reason is required when status is inactive")

	ErrParentRateRequiredWhenCurrencySet = errors.New("parent rate is required when parent currency is set")
	ErrParentCurrencyRequiredWhenRateSet = errors.New("parent currency is required when parent rate is set")
	ErrInvalidParentCurrency             = errors.New("invalid parent currency. Must be KRW, CAD, YEN, or PHP")
	ErrInvalidParentRate                 = errors.New("invalid parent rate")
	ErrParentRateCannotBeNegative        = errors.New("parent rate cannot be negative")

	ErrFirstNameRequired    = errors.New("first name is required")
	ErrLastNameRequired     = errors.New("last name is required")
	ErrBirthdateRequired    = errors.New("birthdate is required")
	ErrAddressRequired      = errors.New("address is required")
	ErrMobileNumberRequired = errors.New("mobile number is required")
	ErrEmailRequired        = errors.New("email is required")
	ErrInvalidEmailAddress  = errors.New("invalid email address")
	ErrInvalidSex           = errors.New("invalid sex. Must be M or F")
	ErrPasswordRequired     = errors.New("password is required")
	ErrInvalidPassword      = errors.New("password must be 8-32 characters with uppercase, lowercase, number, and symbol (!@#$%^&*?)")
	ErrPasswordsDoNotMatch  = errors.New("passwords do not match")

	ErrMissingToken     = errors.New("missing token")
	ErrTokenAlreadyUsed = errors.New("token already used")
	ErrInvalidToken     = errors.New("invalid token")
	ErrTokenExpired     = errors.New("token expired")

	ErrAssignedTeacherRequired     = errors.New("at least one assigned teacher is required")
	ErrDuplicateTeacherAssignment  = errors.New("duplicate teacher assignment")
	ErrInvalidAssignedTeacher      = errors.New("invalid assigned teacher")
	ErrStudentNotAssignedToTeacher = errors.New("student is not assigned to this teacher")
	ErrInvalidRelatedStudent       = errors.New("invalid related student")
	ErrStudentCannotRelateToSelf   = errors.New("a student cannot be related to themselves")
	ErrRelatedStudentNotFound      = errors.New("related student not found")

	ErrInvalidDocumentType   = errors.New("[DOCUMENTS] invalid document type")
	ErrInvalidDocumentStatus = errors.New("[DOCUMENTS] invalid document status")

	ErrUploadedFileEmpty         = errors.New("[DOCUMENTS] Uploaded file is empty")
	ErrDocumentFileTooLarge      = errors.New("[DOCUMENTS] File is too large. Maximum size is 5 MB.")
	ErrInvalidDocumentImage      = errors.New("[DOCUMENTS] Invalid image file. Please upload a PNG or JPEG image.")
	ErrFailedToReadUploadedFile  = errors.New("[DOCUMENTS] Failed to read uploaded file")
	ErrInvalidPDFFile            = errors.New("[DOCUMENTS] Invalid PDF file")
	ErrUnsupportedDocumentFormat = errors.New("[DOCUMENTS] Unsupported file format. Please upload PNG, JPEG, JPG, or PDF.")

	ErrAvatarUploadedFileEmpty      = errors.New("[AVATAR] Uploaded file is empty")
	ErrAvatarFileTooLarge           = errors.New("[AVATAR] File is too large. Maximum size is 2 MB.")
	ErrInvalidAvatarImage           = errors.New("[AVATAR] Invalid image file. Please upload a JPEG or PNG image.")
	ErrFailedToReadUploadedImage    = errors.New("[AVATAR] Failed to read uploaded image")
	ErrUnsupportedAvatarImageFormat = errors.New("[AVATAR] Unsupported image format. Please upload a JPEG or PNG image.")

	ErrTeacherNotFoundInReportSummaries = errors.New("[REPORTS] teacher not found in report summaries")

	ErrFeatureFlagRoleRequired = errors.New("[FEATURE FLAGS] at least one role must be selected")

	ErrFfprobeUnavailable            = errors.New("[INTRO VIDEO] ffprobe unavailable")
	ErrInvalidIntroVideoStatus       = errors.New("[INTRO VIDEO] invalid intro video status")
	ErrIntroVideoUploadPrepareFailed = errors.New("[INTRO VIDEO] Failed to prepare upload")
	ErrIntroVideoSaveFailed          = errors.New("[INTRO VIDEO] Failed to save video")
	ErrIntroVideoFileEmpty           = errors.New("[INTRO VIDEO] Uploaded file is empty")
	ErrIntroVideoFileTooLarge        = errors.New("[INTRO VIDEO] File is too large. Maximum size is 20 MB.")
	ErrUnsupportedIntroVideoFormat   = errors.New("[INTRO VIDEO] Unsupported file format. Please upload MP4, WebM, MOV, AVI, MKV, OGV, M4V, or 3GP.")
	ErrInvalidIntroVideoFile         = errors.New("[INTRO VIDEO] Invalid video file")
	ErrIntroVideoReadFailed          = errors.New("[INTRO VIDEO] Failed to read uploaded file")
	ErrInvalidIntroVideoContent      = errors.New("[INTRO VIDEO] Invalid video file. Please upload a valid video.")
	ErrEmptyIntroVideoDuration       = errors.New("[INTRO VIDEO] empty duration")
)
